# kein Zugriff von auﬂen
server.address: 127.0.0.1

#spring.h2.console.enabled: true
#spring.h2.console.path: /h2
spring.datasource.username:
spring.datasource.password:
spring.datasource.url: jdbc:h2:~/hockey-liga-manger-h2db;DB_CLOSE_ON_EXIT=FALSE
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update