# underscores, keine Bindestriche, sonst SQL Probleme! Der Dateiname erscheint in der SQL Query!
database-file: ~/hockey_liga_manger_h2db

spring.profiles.include: initdata

# kein Zugriff von außen
server:
  address: "localhost"
  compression:
    enabled: true
    min-response-size: 100
    mime-types: application/json, text/html, text/css, application/javascript

#spring.h2.console.enabled: true
#spring.h2.console.path: /h2
spring.datasource.username:
spring.datasource.password:
spring.datasource.url: jdbc:h2:${database-file};DB_CLOSE_ON_EXIT=FALSE
spring:
  jpa:
    open-in-view: false
    hibernate:
      # durch das ddl-auto beginnt h2 erst die persistierten
      # Daten auch beim nächsten startup zu nutzen
      ddl-auto: update

