initdata:
  spieler:
    - id: a2a7c774-0c88-4baf-8845-b6222ebe1b71
      vorname: SpielerVorname1
      nachname: SpielerVorname1
    - id: 7007b773-2f95-42a4-a3df-b6892551c362
      vorname: SpielerVorname2
      nachname: SpielerNachname2
    - id: f971dd81-7590-4a89-9e55-c64a15cdcbd5
      vorname: SpielerVorname3
      nachname: SpielerNachname3
    - id: 47a56f72-8491-4548-be7a-e8b29a8863fe
      vorname: SpielerVorname4
      nachname: SpielerNachname4
    - id: fc4cf4f3-1458-44f8-94fd-b6f1829ada91
      vorname: SpielerVorname5
      nachname: SpielerNachname5
    - id: b6ef7515-2dcc-425b-a3d9-ce931743f444
      vorname: SpielerVorname6
      nachname: SpielerNachname6

  teams:
    - name: Team1
      id: 0dea5a22-4d26-4402-a6d7-4c9b4dd99c6d
      spielerIdList:
        - a2a7c774-0c88-4baf-8845-b6222ebe1b71
        - 7007b773-2f95-42a4-a3df-b6892551c362
        - f971dd81-7590-4a89-9e55-c64a15cdcbd5
    - name: Team2
      id: 0b29b67c-5b03-4c76-b99f-f36b8bbb8833
      spielerIdList:
        - 47a56f72-8491-4548-be7a-e8b29a8863fe
        - fc4cf4f3-1458-44f8-94fd-b6f1829ada91
    - name: Team3

  spielberichte:
    - teamHeimId: 0dea5a22-4d26-4402-a6d7-4c9b4dd99c6d
      teamGastId: 0b29b67c-5b03-4c76-b99f-f36b8bbb8833
      schiedsrichter1: Herr Blümel
      schiedsrichter2: Herr Mustermann
      zeitnehmer: Mr. Zeitstopper
      zuschauer: 42
      ort: Dresden Trainingshalle
      beginTimeString: "2019-03-12T19:00"
      heimSpielerTorEreignisList:
        - time: 1
          schuetzeId: a2a7c774-0c88-4baf-8845-b6222ebe1b71
          firstAssistId: f971dd81-7590-4a89-9e55-c64a15cdcbd5
        - time: 20
          schuetzeId: f971dd81-7590-4a89-9e55-c64a15cdcbd5
          firstAssistId: f971dd81-7590-4a89-9e55-c64a15cdcbd5
      heimSpielerStrafEreignisList:
        - spielerId: f971dd81-7590-4a89-9e55-c64a15cdcbd5
          rv: 9
          dauer: 2
      gastSpielerTorEreignisList:
        - time: 16
          schuetzeId: fc4cf4f3-1458-44f8-94fd-b6f1829ada91
          firstAssistId: 47a56f72-8491-4548-be7a-e8b29a8863fe



